name: Python_1D_simulations

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      #- name: Install Python dependencies
      #  run: py-actions/py-dependency-install@v4

      - name: Verify main.py exists
        run: |
          if [ ! -f src/main.py ]; then
            echo "Error: main.py not found!" && exit 1;
          fi

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll deps
        run: |
              cd docs
              bundle install

      - name: Build Jekyll site
        run: |
              cd docs
              bundle exec jekyll build --baseurl "/${{ github.event.repository.name }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
