name: Python_1D_simulations

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: py-actions/py-dependency-install@v4

      - name: Verify main.py exists
        run: |
          if [ ! -f illustration/main.py ]; then
            echo "Error: main.py not found!" && exit 1;
          fi